---
- name: Check that Composer is installed
  stat: path=/usr/bin/composer
  register: composer_installed

- name: "Download Composer"
  become: true
  command: curl -o installer.php https://getcomposer.org/installer
  when: composer_installed.stat.exists == False

- name: "Install Composer"
  become: true
  command: php -f installer.php
  when: composer_installed.stat.exists == False

- name: "Make Composer available globally"
  become: true
  command: mv composer.phar /usr/bin/composer
  when: composer_installed.stat.exists == False

- name: "Make Composer executable"
  become: true
  command: chmod +x /usr/bin/composer
  when: composer_installed.stat.exists == False

- name: "Remove Composer install file"
  become: true
  command: rm -f installer.php
  when: composer_installed.stat.exists == False
